#!/bin/bash -e

args=()
all=0

while read -r line; do
    if [[ $line != */vmlinuz ]]; then
        # triggers when it's a change to usr/lib/initcpio/*
        all=1
        continue
    fi

    if ! read -r pkgbase > /dev/null 2>&1 < "${line%/vmlinuz}/pkgbase"; then
        # if the kernel has no pkgbase, we skip it
        continue
    fi

    if ! read -r kernelbase > /dev/null 2>&1 < "${line%/vmlinuz}/kernelbase"; then
        # this kernel has no kernelbase, use pkgbase
        kernelbase="${pkgbase}"
    fi

    distributor_id=$(lsb_release -i | sed "s/.*:\s//")
    root_uuid=$(findmnt -no UUID '/')

    esp_path=$(bootctl -p)
    install_path="${esp_path}/EFI/${distributor_id}-${root_uuid}"

    preset="/etc/mkinitcpio.d/${pkgbase}.preset"

    # sed expression for following substitutions
    _subst="
      s|%PKGBASE%|${pkgbase}|g
      s|%KERNELBASE%|${kernelbase}|g
      s|%INSTALL_PATH%|${install_path}|g
    "

    if [[ ! -e $preset ]]; then
        if [[ -e $preset.pacsave ]]; then
            # move the pacsave to the template
            mv "${preset}.pacsave" "$preset"
        else
            # create the preset from the template
            sed "${_subst}" /usr/share/mkinitcpio/hook.preset \
                | install -Dm644 /dev/stdin "$preset"
        fi
    fi

    # always install the kernel
    install -Dm644 "${line}" "${install_path}/vmlinuz-${kernelbase}"
    ln -sf "${install_path}/vmlinuz-${kernelbase}" "/boot/vmlinuz-${kernelbase}"

    # compound args for each kernel
    args+=(-p "${pkgbase}")
done

if (( all )) && compgen -G /etc/mkinitcpio.d/"*.preset" > /dev/null; then
    # change to use all presets
    args=(-P)
fi

if (( ${#args[@]} )); then
    mkinitcpio "${args[@]}"
fi
